#!/usr/bin/env python3
# vim:fileencoding=utf-8

import os, re, sys
import lxml.html
from httpsession import Session, Operation
from qgmail import *
from getpass import getpass

class QMail(Session, Operation):
  loginUrl = 'https://mail.qq.com/cgi-bin/loginpage'
  loginVerifyImage = 'https://mail.qq.com/cgi-bin/getverifyimage?aid=23000101&f=html&ck=1'
  loginPostUrl = 'https://mail.qq.com/cgi-bin/login?sid=,2,zh_CN'
  def try_login(self):
    # TODO 使用 cookie 登录
    r = self.request(self.loginUrl)
    r.read()
    r = self.request(self.loginVerifyImage)
    open('verifyimage.png', 'wb').write(r.read())
    pid = os.fork()
    if pid == 0:
      os.execlp('feh', 'feh', 'verifyimage.png')
    verifycode = input('验证码: ')
    os.kill(pid, 15)
    r = self.request(self.loginPostUrl, {
      'sid': ',2,zh_CN',
      'firstlogin': 'false',
      'starttime': '1295618620302',
      'redirecturl': '',
      'f': 'html',
      'p': getpass(),
      'ept': '0',
      'delegate_url': '',
      's': '',
      'ts': '1295618601',
      'from': '',
      'ppp': '',
      'chg': '0',
      'target': '',
      'checkisWebLogin': '15',
      'uin': '583567462',
      'aliastype': '@qq.com',
      'pp': '00000000',
      'verifycode': verifycode,
      'ss': '1',
    })
    page = r.read().decode('gb18030')
    open('loginresult', 'w').write(page)
    try:
      m = re.search(r'<script>(.*)</script></html>', page, re.DOTALL)
      script = m.group(1)
      m = re.search(r'urlHead="([^"]+)"', script)
      url = m.group(1)
      self.urlHead = url
      m = re.search(r'targetUrl = [^"]+"([^"]+)"', script)
      sidpart = m.group(1)
      url += sidpart
      self.sid = sidpart[sidpart.find('=')+1:]
      print('sid is', self.sid)
      m = re.search(r'targetUrl\+="([^"]+)"', script)
      url += m.group(1)
    except AttributeError:
      print('登录出错。', file=sys.stderr)
      sys.exit(1)

    r = self.request(url)
    page = r.read().decode('gb18030')
    open('loginresult2', 'w').write(page)
    r = self.request('{self.urlHead}mail_list?sid={self.sid}&folderid=8&page=0&t=mail_list_group&loc=folderlist,,,8#stattime=1295619572311'.format(self=self))
    page = r.read().decode('gb18030')
    open('groupmail', 'w').write(page)

    mails = parseGroupMails(page)
    url = self.urlHead + mails[1].geturl() % self.sid
    r = self.request(url)
    page = r.read().decode('gb18030')
    open('singlemail', 'w').write(page)

    posts = parseSingleGroupMail(page)
    for p in posts:
      print(p)

if __name__ == '__main__':
  QMail('cookie').try_login()
